[profile.default]
src = "src"
out = "out"
load_from_env_file = true
libs = ["lib"]
solc_version = "0.8.20"
remappings = [
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/',
    '@chainlink/contracts/=node_modules/@chainlink/contracts/',
    'forge-std/=lib/forge-std/src/',
    
]


[rpc_endpoints]
avalanche_fuji = "https://avax-fuji.g.alchemy.com/v2/bYIbSPa2_ReoZHLM4-5LHaJ_HcFJsXbL"
ethereum_sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
sonic_blaze = "https://sonic-blaze-rpc.publicnode.com"
monad_testnet = "https://testnet-rpc.monad.xyz"
