[profile.default]
src = "src"
out = "out"
load_from_env_file = true
libs = ["lib"]
solc_version = "0.8.20"
remappings = [
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/',
    '@chainlink/contracts/=node_modules/@chainlink/contracts/',
    'forge-std/=lib/forge-std/src/',
    
]


